version: "3.9"
services:
  web:
    depends_on: 
      - postgres_db
    build:
      context: ./web
      dockerfile: Dockerfile
    image: django-k8s:v1
    env_file: ./web/.env
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
  postgres_db:
    image: postgres
    restart: always
    command: -p 5434
    env_file:
      - web/.env
    expose:
      - 5434
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    restart: always
    image: redis
    expose:
      - 6388
    ports:
      - "6388:6388"
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6388

volumes:
  postgres_data:
  redis_data:
