apiVersion: v1
kind: Service
metadata:
  name:  load-balancer
spec:
  selector:
    app:  django-app
  type:  LoadBalancer 
  ports:
  - name:  nginx-port
    port:  80
    targetPort:  8080
    protocol: TCP