apiVersion: v1
kind: Pod
metadata:
  name: django-pod
  labels:
    name: django-pod
spec:
  containers:
  - name: django-pod
    image: funsojoba/dk8s
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8000
