apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app-service
  type: ClusterIP
  ports:
  - name: app-service
    port: 8000
    targetPort: 8000
    protocol: TCP